# Generated by Django 4.2.16 on 2024-10-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
